name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean install
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install
          npm list

      - name: Type check
        run: |
          npx tsc --noEmit
        continue-on-error: true

      - name: Build
        run: |
          npm run build
          ls -la dist/
        env:
          CI: true
          NODE_ENV: production

      - name: Debug info
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Directory structure:"
          ls -R
          echo "Package.json:"
          cat package.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
